### ISSUE TITLE
[Bug]: Missing biome lang entry

### ISSUE THREAD

**Issue by xR4YM0ND** [HexagonNico/UndergroundJungle#11]
While using TravelerZ mod i found out that the biome lang is missing

![2023-12-31_17 49 40](https://github.com/HexagonNico/UndergroundJungle/assets/97298005/ecdbea99-78ca-4e0b-a3a8-d91c16171204)

- Fabric 1.20.1

**Comment by HexagonNico** [comment]
Resolved by b4cc0c915a5eee422c460914be9339f2cef933ad

Thank you for your contribution!
