### ISSUE TITLE
Biome tags needed

### ISSUE THREAD

**Issue by Mechalopa** [HexagonNico/UndergroundJungle#12]
I think the underground jungle biome should be registered for the following biome tags (sorry, I don't know about tags for fabric)
- `minecraft:is_jungle`
- `minecraft:is_overworld`
- `minecraft:stronghold_biased_to`
- `minecraft:has_structure/mineshaft`
- `forge:is_hot/overworld`
- `forge:is_wet/overworld`
- `forge:is_cave`
- `forge:is_lush` (optional)

**Comment by HexagonNico** [comment]
Resolved by d5b1f5045f9ced9e901aa82c0ed6a6ef792c2b25

Thank you for your contribution!
