### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Natedogwoooof** [HexagonNico/UndergroundJungle#19]
[crash-2024-03-15_09.32.56-client.txt](https://github.com/HexagonNico/UndergroundJungle/files/14625024/crash-2024-03-15_09.32.56-client.txt)

underground jungle mushroom placemt crash

**Comment by HexagonNico** [comment]
Related to #6 

Sorry for the late reply, I was busy with IRL stuff.

This seemed to be caused by cocoa beans trying to generate underground, which has now been fixed for 1.20.1.
The fix for other versions will come soon.

**Comment by HexagonNico** [comment]
Resolved for 1.19.4 and 1.20.3 as well.
