### ISSUE TITLE
[1.20.1] Crash on World Generation

### ISSUE THREAD

**Issue by Reshy** [HexagonNico/UndergroundJungle#21]
https://pastebin.com/Jkeb9bYr

Disabling the mod fixed the issue and allowed it to generate worlds and load correctly.

**Comment by HexagonNico** [comment]
Hi. Thanks for the report.

The biome in version 1.20.x was using the `jungle_and_forest` music like in 1.19, but it was removed in 1.20 and replaced with just `jungle`. Problem has been fixed now.
