### ISSUE TITLE
[1.20.1]  Underground jungles can spawn on the surface, leading to empty biomes.

### ISSUE THREAD

**Issue by Reshy** [HexagonNico/UndergroundJungle#4]
![image](https://github.com/HexagonNico/UndergroundJungle/assets/2096384/d53e3ead-1cd1-4ed3-9da6-39d8cb0e5532)
![image](https://github.com/HexagonNico/UndergroundJungle/assets/2096384/0a5e52ec-d221-45c2-8eda-482225b043fb)

Not sure what causes this, might be related to Terrablender but the biome can spawn on the surface.  Might be worth making terrain generation for if it spawns above Y71, maybe a dense jungle that's dark with a dense canopy?

**Comment by HexagonNico** [comment]
Do you have other world generation mods installed like Terralith? It might be affecting the climate parameters, because I haven't seen it happening without other mods. I can try increasing the depth of the biome to make sure it generates underground.

**Comment by Reshy** [comment]
Maybe Wythers?

**Comment by HexagonNico** [comment]
I changed the generation of the biome with f1dfd1d

Now it generates at the same height as the vanilla lush cave and dripstone cave. Hopefully this should fix the issue.

**Comment by Shadownite64** [comment]
This was kinda a cool bug tho, almost like a new biome entirely perfect for building
